= Server Groups
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: server groups, curl, rest

This document, as well as the rest of the documents that make up the xref:rest-api-reference.adoc[Mule Management Console REST API Reference Guide], are a technical reference only. This document does not provide contextual information such as instructions, use cases or scenarios. To understand this document, you should be familiar with https://www.mulesoft.com/resources/esb/what-mule-esb[MULE ESB], Server Groups and the xref:using-the-management-console-api.adoc[REST API].

[cols="2*"]
|===
|*Host* |localhost
|*Port* |8080
|*Deployed app* |mmc.war
|*User/Password* |admin/admin
|===

For a detailed description of the format used in this document, consult xref:rest-api-reference.adoc[Content Organization and Conventions].

*/api/serverGroups*

[cols="2*a"]
|===
|*POST*
|CREATE
|===

Creates a new Server Group.

[.ex]
=====
[discrete.view]
=== STUDIO Visual Editor

[discrete]
==== JSON

[source,text,linenums]
----
{
  "name": "NewGroupName"
}
----

[%header,cols="4*"]
|===
|Key |Type |Summary |Child of
|name |String |Name of the Server Group to be created |—
|===

[discrete]
==== Using CURL on Windows

[source,text,linenums]
----
 curl --basic -u admin:admin -d "{ \"name\" : \"NewGroupName\" }" --header "Content-Type: application/json" http://localhost:8080/mmc/api/serverGroups
----

[discrete]
==== Using CURL on Linux

[source,text,linenums]
----
 curl --basic -u admin:admin -d '{ "name" : "NewGroupName" }" --header 'Content-Type: application/json' http://localhost:8080/mmc/api/serverGroups
----

[discrete.view]
=== Response

[discrete]
==== JSON

[source,json,linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[%header,cols="4*"]
|===
|Key |Type |Summary |Child of
|name |String |Name of the created Server Group |—
|id |String |MMC ID for the Server Group. |—
|serverCount |String |Number of servers assigned to the Server Group |—
|href |String |Full link to the Server Group resource on which you can perform an operation |—
|===

[discrete.view]
=== Common Return codes

[cols="2*a"]
|===
|*201* |The request has been fulfilled and resulted in a new Server Group being created
|*409* |A server group with that name already exists
|*500* |Error while creating a Server Group
|===

[discrete.view]
=== MMC version

[cols="2*a"]
|===
|From |3.2.2
|===

=====

[cols="2*a"]
|===
|*GET*
|LIST ALL
|
|===

Lists all available Server Groups.

[.ex]
=====
[discrete.view]
=== STUDIO Visual Editor

[discrete]
==== Using CURL

[source,text,linenums]
----
 curl --basic -u admin:admin http://localhost:8080/mmc/api/serverGroups
----

[discrete.view]
=== Response

[discrete]
==== JSON

[source,json,linenums]
----
{
  "total": 1,
  "data": [
    {
      "name": "NewGroupName",
      "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
      "serverCount": 0,
      "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
    }
  ]
}
----

[%header,cols="4*"]
|===
|Key |Type |Summary |Child of
|total |Integer |The total number of Server Groups |—
|data |Array |An array of server group types |—
|name |String |The identifying name of the server group |data
|id |String |The server group identifier |data
|serverCount |Integer |The number of servers in the server group |data
|href |String |Full link to the Server Group resource to which you can perform an operation |data
|===

[discrete.view]
=== Common Return codes

[cols="2*a"]
|===
|*200* |The operation was successful
|===

[discrete.view]
=== MMC version

[cols="2*a"]
|===
|From |3.2.2
|===

=====

*/api/serverGroups/\{serverGroupId}*

[cols="3*a"]
|===
|*GET*
|LIST
|
|===

Lists details for a specific Server Group.

[.ex]
=====
[discrete.view]
=== Request

[discrete]
==== SYNTAX

GET http://localhost:8080/mmc/api/serverGroups/\{serverGroupId}

[%header,cols="4*"]
|===
|Key |Type |Summary |Child of
|serverGroupdId |String |ID of the server group to be listed. Invoke LIST ALL to obtain it |—
|===

[discrete]
==== Using CURL

[source,text,linenums]
----
 curl --basic -u admin:admin http://localhost:8080/mmc/api/serverGroups/37f6cd27-98b3-44b1-97e6-50b75e47f8c1
----

[discrete.view]
=== Response

[discrete]
==== JSON

[source,json,linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[%header,cols="4*"]
|===
|Key |Type |Summary |Child of
|name |String |  |—
|id |String |Id of the Server Group |—
|serverCount |Number of servers belonging to the Server Group |  |—
|href |String |Full link to the Server Group resource |—
|===

[discrete.view]
=== Common Return codes

[cols="2*a"]
|===
|*200* |The operation was successful
|*404* |A server with that ID was not found
|===

[discrete.view]
=== MMC version

[cols="2*a"]
|===
|From |3.2.2
|===
=====

[cols="2*a"]
|===
|*PUT*
|RENAME
|
|===

Renames a specific Server Group.

[.ex]
=====
[discrete.view]
=== Request

[discrete]
==== JSON

[source,json,linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[%header,cols="4*"]
|===
|Key |Type |Summary |Child of
|name |String |Name of the created Server Group |—
|id |String |MMC ID of the Server Group |—
|serverCount |String |Number of servers assigned to the Server Group |—
|href |String |Full link to the Server Group resource on which you can perform an operation |—
|===

[discrete]
==== Using CURL on Windows

[source,text,linenums]
----
 curl --basic -u admin:admin -X PUT -d "{\"name\":\"NewName\",\"id\":\"330d9139-4462-4e36-b76c-569776cc3da9\",\"href\": \"http://localhost:8080/mmc/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9\",\"serverCount\":0}" --header "Content-Type:application/json" http://localhost:8080/mmc/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9
----

[discrete]
==== Using CURL on Linux

[source,text,linenums]
----
curl --basic -u admin:admin -X PUT -d '{"name":"NewName","id":"330d9139-4462-4e36-b76c-569776cc3da9","href": "http://localhost:8080/mmc/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9","serverCount":0}' --header 'Content-Type:application/json' http://localhost:8080/mmc/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9
----

[discrete.view]
=== Response

[discrete]
==== JSON

[source,json,linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[%header,cols="4*"]
|===
|Key |Type |Summary |Child of
|name |String |Name of the created Server Group |—
|id |String |MMC ID of the Server Group |—
|serverCount |String |Number of servers assigned to the Server Group |—
|href |String |Full link to the Server Group resource to which you can perform an operation |—
|===

[discrete.view]
=== Common Return codes

[cols="2*a"]
|===
|*200* |The operation was successful
|*500* |Error while renaming a Server Group
|===

[discrete.view]
=== MMC version

[cols="2*a"]
|===
|From |3.2.2
|===

=====

[cols="3*a"]
|===
|*DELETE*
|REMOVE
|
|===

Removes a specific Server Group.

[.ex]
=====
[discrete.view]
=== Request

[discrete]
==== SYNTAX

DELETE http://localhost:8080/mmc/api/serverGroups/\{serverGroupId}

[%header,cols="4*"]
|===
|Key |Type |Summary |Child of
|serverGroupdId |String |ID of the server group to be removed. Invoke LIST ALL to obtain it |—
|===

[discrete]
==== Using CURL

[source,text,linenums]
----
 curl --basic -u admin:admin -X DELETE http://localhost:8080/mmc/api/serverGroups/37f6cd27-98b3-44b1-97e6-50b75e47f8c1
----

[discrete.view]
=== Response

[discrete]
==== JSON

`200 OK`

[discrete.view]
=== Common Return codes

[cols="2*a"]
|===
|*200* |The operation was successful
|===

[discrete.view]
=== MMC version

[cols="2*a"]
|===
|From |3.2.2
|===
=====